import './kccacheproxy-boundary.test.js'
import './recommendation-characterization.test.js'
import './recommendation-worker-service.test.js'
import './strategy-room-view.test.js'
import './webui-ipc.test.js'
