export const ACCOUNT_CHANNEL = 'recommendation:account-summary'
export const MAP_OPTIONS_CHANNEL = 'recommendation:map-options'
export const RECOMMEND_CHANNEL = 'recommendation:recommend'
export const EXPEDITION_SUMMARY_CHANNEL = 'recommendation:expedition-summary'
export const EXPEDITION_PLAN_CHANNEL = 'recommendation:expedition-plan'
export const RESOURCE_LEDGER_SUMMARY_CHANNEL = 'recommendation:resource-ledger-summary'
